### ISSUE TITLE
_

### ISSUE THREAD

**Issue by ghost** [h0MER247/swGL#8]
_

**Comment by adamschackart** [comment]
That should only stop compilation if you're passing 'warnings as errors' (-Werror) as an argument to Clang/GCC. The compiler is basically telling you that anything other than cdecl is ignored on x64, which is a meaningless and overly pedantic warning IMHO.

You need to provide replacements for certain win32/gdi functions like WindowFromDC, GetClientRect, and most notably SetDIBitsToDevice unless you're really prepared to get in and hack at the internals of this library. There are also a few things you'll need to do in order to port this library to a 64-bit platform - the original author uses 'unsigned int' in place of 'uintptr_t' in at least one place if I recall correctly.

My recommendation would be to use something like SwiftShader or osmesa for software 3D rendering.

**Comment by briancullinan** [comment]
It's actually for web build of Quake 3 based on QuakeJS. I was planning on having to rewrite some sort of output buffer. Thank you for sharing SwiftShader, I wonder if Google made any shortcuts to get it to work in their web browser.
